apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: services
  name: <%= service %>-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: virtuatable-<%= service %>
spec:
  rules:
    - http:
        paths:
          - path: "<%= prefix %>(/|$)(.*)"
            pathType: Prefix
            backend:
              service:
                name: <%= service %>-service
                port:
                  number: 80