apiVersion: v1
kind: Service
metadata:
  namespace: <%= service %>
  name: <%= service %>-service
  labels:
    app: virtuatable-<%= service %>
spec:
  selector:
    app: virtuatable-<%= service %>
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9292